homework/homework/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('quotesapp.urls')),
]

homework/quotesapp/urls.py
from django.urls import path
from . import views

app_name = 'quotesapp'

urlpatterns = [
    path('', views.main, name='main'),
    path('<int:page>', views.main, name='main_paginate'),
    path('quote/', views.quote, name='quote'),
    path('author/', views.author, name='author'),
    path('tag/', views.tag, name='tag'),
    path('author_page/<fullname>', views.detail, name='author_page'),
]

homework/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.signupuser, name='signup'),
    path('login/', views.loginuser, name='login'),
    path('logout/', views.logoutuser, name='logout'),
]

homework/quotesapp/models.py
from django.db import models

# Create your models here.

class Author(models.Model):
    fullname = models.CharField(max_length=50)
    born_date = models.CharField(max_length=50)
    born_location = models.CharField(max_length=150)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)


class Tag(models.Model):
    name = models.CharField( null=False, unique=True)


class Quote(models.Model):
    quote = models.TextField()
    tags = models.ManyToManyField(Tag)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, default=None, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

homework/users/models.py
from django.db import models

# Create your models here.

homework/homework/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):
    username = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput())

    password1 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput())
    password2 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']

homework/quotesapp/forms.py
from django.forms import ModelForm, CharField, TextInput

from .models import Tag, Quote, Author


class TagForm(ModelForm):

    name = CharField(min_length=3, max_length=25, required=True, widget=TextInput())
    
    class Meta:
        model = Tag
        fields = ['name']

class QuoteForm(ModelForm):

    quote = CharField(min_length=5, required=True, widget=TextInput())
    

    class Meta:
        model = Quote
        fields = ['quote']
        exclude = ['tags', 'author']

class AuthorForm(ModelForm):

    fullname = CharField(max_length=50, required=True, widget=TextInput())
    born_date = CharField(max_length=50, required=True, widget=TextInput())
    born_location = CharField(max_length=150, required=True, widget=TextInput())
    description = CharField(max_length=150, required=True, widget=TextInput())


    
    class Meta:
        model = Author
        fields = ['fullname', 'born_date', 'born_location', 'description']

homework/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):
    username = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput())

    password1 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput())
    password2 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']

class LoginForm(AuthenticationForm):

    class Meta:
        model = User
        fields = ['username', 'password']

homework/quotesapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.paginator import Paginator

from .forms import TagForm, QuoteForm, AuthorForm

from .models import Quote, Tag, Author


# from .utils import get_mongodb

# Create your views here.
def main(request, page=1):
    per_page = 10
    quotes = Quote.objects.all()
    tags = Tag.objects.all
    paginator = Paginator(quotes, per_page)
    quotes_on_page = paginator.get_page(page)
    return render(request, 'quotesapp/index.html', context={'quotes': quotes_on_page, 'tags':tags})

def quote(request):
    tags = Tag.objects.all()
    author = Author.objects.all()

    if request.method == 'POST':
        form = QuoteForm(request.POST)
        if form.is_valid():
            new_quote = form.save()

            choice_tags = Tag.objects.filter(name__in=request.POST.getlist('tags'))
            for tag in choice_tags.iterator():
                new_quote.tags.add(tag)

            choice_author = Author.objects.filter(fullname=request.POST.get('author')).first()
            new_quote.author = choice_author
            new_quote.save()


            return redirect(to='quotesapp:main')
        else:
            return render(request, 'quotesapp/quote.html', {"tags": tags, 'form': form, 'author':author})

    return render(request, 'quotesapp/quote.html', {"tags": tags, 'author':author, 'form': QuoteForm()})

def author(request):
    if request.method == 'POST':
        form = AuthorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quotesapp:main')
        else:
            return render(request, 'quotesapp/author.html', {'form': form})

    return render(request, 'quotesapp/author.html', {'form': AuthorForm()})

def tag(request):
    if request.method == 'POST':
        form = TagForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quotesapp:main')
        else:
            return render(request, 'quotesapp/tag.html', {'form': form})

    return render(request, 'quotesapp/tag.html', {'form': TagForm()})


def detail(request, fullname):
    author = get_object_or_404(Author, fullname=fullname)
    return render(request, 'quotesapp/author_page.html', {"author": author})

homework/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from .forms import RegisterForm, LoginForm



def signupuser(request):
    if request.user.is_authenticated:
        return redirect(to='quotesapp:main')

    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quotesapp:main')
        else:
            return render(request, 'users/signup.html', context={"form": form})

    return render(request, 'users/signup.html', context={"form": RegisterForm()})


def loginuser(request):
    if request.user.is_authenticated:
       return redirect(to='quotesapp:main')

    if request.method == 'POST':
        user = authenticate(username=request.POST['username'], password=request.POST['password'])
        if user is None:
            messages.error(request, 'Username or password didn\'t match')
            return redirect(to='users:login')

        login(request, user)
        return redirect(to='quotesapp:main')

    return render(request, 'users/login.html', context={"form": LoginForm()})

@login_required
def logoutuser(request):
    logout(request)
    return redirect(to='quotesapp:main')

homework/quotesapp/templates/quotesapp/author.html
{% extends 'quotesapp/base.html' %}

{% block content %}

<div class="mb-3 border border-secondary text-center">
    
    <form method="POST" action="{% url 'quotesapp:author' %}" class="form-label p-5">
        {% csrf_token %}
        <p class="badge text-bg-primary text-wrap">Add Author</p>
        <div style="padding: 10px">
            <label class="form-label"> Fullname:<br>
                {{ form.fullname }}
            </label>
            <span>{{ form.errors.fullname }}</span>
        </div>
        <div style="padding: 10px">
            <label class="form-label"> Born date:<br>
                {{ form.born_date }}
            </label>
            <span>{{ form.errors.born_date }}</span>
        </div>
        <div style="padding: 10px">
            <label class="form-label"> Born location:<br>
                {{ form.born_location }}
            </label>
            <span >{{ form.errors.born_location }}</span>
        </div>
    
        <div style="padding: 10px">
            <label class="form-label"> Description:<br>
                <textarea name="description" rows="10" cols="50" required>{{ form.description.value|default:'' }}</textarea>
            </label>
            <span>{{ form.errors.description }}</span>
        </div>
    
        <div class="grid">
            <button type="submit" class="btn btn-success">Submit</button>
            <button type="reset" class="btn btn-secondary">Reset</button>
        </div>
    </form>
</div>


{% endblock %}

homework/quotesapp/templates/quotesapp/author_page.html
{% extends 'quotesapp/base.html' %}

{% block content %}

<div class="container pt-5">
    <div>
        <p>{{author.fullname}}</p>
        <p>{{author.born_date}}</p>
        <p>{{author.born_location}}</p>
        <p>{{author.description}}</p>
    </div>

</div>

{% endblock %}

homework/quotesapp/templates/quotesapp/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <title>Quote information</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'quotesapp/style.css' %}">
</head>

<body>

    <div class="container">
        <div class="row header-box pt-3">
            <div class="col-md-8">
                <h1>
                    <a href="/" style="text-decoration: none">Quotes</a>
                </h1>
            </div>
            {% if user.is_authenticated %}
            <div class="col-md-4">
                <p>
                    <a href="{% url 'quotesapp:tag' %}" role="button" class="btn btn-info">Add Tag</a>
                    <a href="{% url 'quotesapp:quote' %}" role="button" class="btn btn-info">Add Quote</a>
                    <a href="{% url 'quotesapp:author' %}" role="button" class="btn btn-info">Add Author</a>
                    <a href="{% url 'users:logout' %}" class="btn btn-primary">Logout</a>
                </p>
            </div>
            {% else %}
            <div class="col-md-4">
                <p>
    
                    <a href="{% url 'users:signup' %}" class="btn btn-primary">Signup</a>
                    <a href="{% url 'users:login' %}" class="btn btn-primary">Login</a>
                </p>
            </div>
            {% endif %}
        </div>

        {% block content %} {% endblock %}
    
    
    </div>
</body>

</html>

homework/quotesapp/templates/quotesapp/index.html
{% extends 'quotesapp/base.html' %}

{% block content %}

<div class="row">
    <div class="col-md-8">
        {% for quote in quotes %}
        <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
            <span class="text" itemprop="text">
                        {{quote.quote}}
            </span>
            <span>by <small class="author" itemprop="author">{{quote.author.fullname}}</small>
                <a href="{% url 'quotesapp:author_page' quote.author.fullname %}">(about)</a>
            </span>
                <div class="tags">
                    Tags:
                    {% for tag in quote.tags.all %}
                    <a class="tag">{{ tag.name }}</a>
                    {% endfor %}
                </div>
        </div>
                
                
        {% endfor %}
        <nav>
            <ul class="pager">
        
                <li class="previous">
                    <a class="{% if not quotes.has_previous %} disabled {% endif %}"
                        href="{% if quotes.has_previous %} {% url 'quotesapp:main_paginate' quotes.previous_page_number %} {% else %} # {% endif %}">
                        <span aria-hidden="true">←</span> Previous
                    </a>
                </li>
        
        
                <li class="next">
                    <a class="{% if not quotes.has_next %} disabled {% endif %}"
                        href="{% if quotes.has_next %} {% url 'quotesapp:main_paginate' quotes.next_page_number %} {% else %} # {% endif %}">
                        <span aria-hidden="true">→</span> Next
                    </a>
                </li>
        
            </ul>
        </nav>
      
    </div>
</div>

{% endblock %}

homework/quotesapp/templates/quotesapp/quote.html
{% extends 'quotesapp/base.html' %}

{% block content %}

<div class="mb-3 border border-secondary text-center">

    <form method="POST" action="{% url 'quotesapp:quote' %}" class="form-label p-5">
        {% csrf_token %}
        <p class="badge text-bg-primary text-wrap">Add Quote</p>
        <div style="padding: 10px">
            <label> Quote:<br>
                <textarea name="quote" rows="10" cols="50" required>{{ form.quote.value|default:'' }}</textarea>
            </label>
            <span>{{ form.errors.quote }}</span>
        </div>
        <div style="padding: 10px">
            <label> Author:<br>
                <select name="author" required>
                    {% for auth in author %}
                    <option value="{{auth.fullname}}">{{auth.fullname}}</option>
                    {% endfor %}
                </select>
            </label>
        </div>
        <div style="padding: 10px">
            <label> Tags:<br>
                <select name="tags" multiple="multiple" required>
                    {% for tag in tags %}
                    <option value="{{tag.name}}">{{tag.name}}</option>
                    {% endfor %}
                </select>
            </label>
        </div>
        <div class="grid">
            <button type="submit" class="btn btn-success">Submit</button>
            <button type="reset" class="btn btn-secondary">Reset</button>
        </div>
    </form>

</div>

{% endblock %}

homework/quotesapp/templates/quotesapp/tag.html
{% extends "quotesapp/base.html" %}

{% block content %}

<div class="mb-3 border border-secondary text-center">

<form method="POST" action="{% url 'quotesapp:tag' %}" class="form-label p-5">
    {% csrf_token %}
    <p class="badge text-bg-primary text-wrap">Add Tag</p>
    <div style="padding: 10px">
        <label>Enter the tag name:<br>
            {{form.name}}
        </label>
        <span>{{ form.errors.name }}</span>
    </div>
    <div class="grid">
        <button type="submit" class="btn btn-success">Submit</button>
        <button type="reset" class="btn btn-secondary">Reset</button>
    </div>
</form>

</div>

{% endblock %}

homework/users/templates/users/login.html
{% extends 'quotesapp/base.html' %}

{% block content %}

{% if messages %}
<div>
    {% for message in messages %}
    <div {% if message.tags %} class="alert-{{ message.tags }}" {% endif %}>{{ message }}</div>
    {% endfor %}
</div>
{% endif %}

<form action="{% url 'users:login' %}" method="post">
    {% csrf_token %}
    <div>
        <label> Username:
            {{ form.username }}
        </label>
    </div>

    <div>
        <label>Password:
            {{ form.password }}
        </label>
    </div>

    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}

homework/users/templates/users/signup.html
{% extends 'quotesapp/base.html' %}

{% block content %}

<div>
    <h2>Sign Up</h2>
</div>

<form method="post" action="{% url 'users:signup' %}">
    {% csrf_token %}
    <div>
        <label> Username:
            {{ form.username }}
        </label>
        <span>{{ form.errors.username }}</span>
    </div>
    <br>
    <div>
        <label> Password:
            {{ form.password1 }}
        </label>
        <span>{{ form.errors.password1 }}</span>
    </div>
    <div>
        <label> Password confirmation:
            {{ form.password2 }}
        </label>
        <span>{{ form.errors.password2 }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}